force-app/main/default/objects/Appointment__c/Appointment__c.object-meta.xml
<CustomObject>
    <label>Appointment</label>
    <nameField>
        <displayFormat>FA-{0000}</displayFormat>
        <label>Appointment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Appointments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Appointment__c/fields/Doctor__c.field-meta.xml
<CustomField>
    <fullName>Doctor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Doctor</label>
    <referenceTo>Doctors__c</referenceTo>
    <relationshipLabel>Appointments</relationshipLabel>
    <relationshipName>Appointments</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Doctors__c/Doctors__c.object-meta.xml
<CustomObject>
    <label>Doctor</label>
    <nameField>
        <label>Doctors Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Doctors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/AppointmentTriggerHandler.cls
public with sharing class AppointmentTriggerHandler implements ITrigger {
    public void onBeforeInsert() {
        List<Datetime>appointmentDatesNewList = new List<Datetime>();

        for (Appointment__c appointmentNew : (List<Appointment__c>)Trigger.new) {
            appointmentDatesNewList.add(appointmentNew.Appointment_Date__c);
        }
        AppointmentTriggerHelper appointmentHelper=new  AppointmentTriggerHelper(appointmentDatesNewList);


        //compare doctors on the same dates
        for (Appointment__c appointmentNew :  (List<Appointment__c>)Trigger.new) {

            List<Appointment__c>oldDoctorAppointments= appointmentHelper.getDoctorAppointmentsForDateSortedByTime(appointmentNew.Doctor__r,appointmentNew.Appointment_Date__c);
            for (Appointment__c appointmentOld : oldDoctorAppointments) {

                if (appointmentNew.Appointment_Date__c == appointmentOld.Appointment_Date__c) {

                    appointmentNew.addError('This date is already taken,select another');

                }
            }

        }
    }
    public void onBeforeUpdate(){

    }
    public void onBeforeDelete(){

    }
    public void onAfterInsert(){

    }
    public void onAfterUpdate(){

    }
    public void onAfterDelete(){

    }
}