force-app/main/default/objects/Appointment__c/Appointment__c.object-meta.xml
<CustomObject>
    <label>Appointment</label>
    <nameField>
        <displayFormat>FA-{0000}</displayFormat>
        <label>Appointment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Appointments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Appointment__c/fields/Doctor__c.field-meta.xml
<CustomField>
    <fullName>Doctor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Doctor</label>
    <referenceTo>Doctors__c</referenceTo>
    <relationshipLabel>Appointments</relationshipLabel>
    <relationshipName>Appointments</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Doctors__c/Doctors__c.object-meta.xml
<CustomObject>
    <label>Doctor</label>
    <nameField>
        <label>Doctors Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Doctors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/AppointmentTriggerHelper.cls
public with sharing class AppointmentTriggerHelper {
    List<Appointment__c> sameDateAppointments;
    public AppointmentTriggerHandler(List<Datetime> dates) {
        //select records with the same date
        sameDateAppointments = [
                SELECT Appointment_Date__c,Doctor__r.Id,Duration_in_minutes__c
                FROM Appointment__c
                WHERE Appointment_Date__c IN :dates
                ORDER BY Appointment_Date__c ASC
        ];
    }
    public List<Appointment__c>getDoctorAppointmentsForDateSortedByTime(Doctors__c doc, Datetime dateOfAppointment) {
        List<Appointment__c>doctorAppointmentsForDate = new List<Appointment__c>();
        for (Appointment__c appointment : sameDateAppointments) {
            if (appointment.Doctor__r.Id == doc.Id && appointment.Appointment_Date__c.date() == dateOfAppointment) {
                doctorAppointmentsForDate.add(appointment);
            }
        }
        return doctorAppointmentsForDate;
    }
    public Boolean isValidTime(Appointment__c newAppointment, List<Appointment__c>oldAppointments) {
        Time currentAppointmentTime = newAppointment.Appointment_Date__c.timeGmt();

        if (currentAppointmentTime < oldAppointments[0].Appointment_Date__c.timeGmt()) {
            return true;
        }
        if (currentAppointmentTime>oldAppointments[oldAppointments.size()-1].Appointment_Date__c.timeGmt()) {
            return true;
        }
        for (Integer i = oldAppointments.size() - 1; i > 0; i--) {
            Time prevAppointmentTime = oldAppointments[i - 1].Appointment_Date__c.addMinutes(oldAppointments[i - 1].Duration_in_minutes__c.intValue()).timeGmt();
            Time nextAppointmentTime = oldAppointments[i].Appointment_Date__c.timeGmt();

            if (prevAppointmentTime <= currentAppointmentTime &&
                    nextAppointmentTime > currentAppointmentTime.addMinutes(newAppointment.Duration_in_minutes__c.intValue())) {
                return true;
            }
        }
        return false;

    }
}